# Generated by Django 4.0.2 on 2022-02-28 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=120)),
                ('model_name', models.CharField(max_length=120, unique=True)),
                ('price', models.FloatField()),
                ('description', models.TextField(max_length=255)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_name', to='api.company')),
            ],
        ),
    ]
