# Generated by Django 4.0.2 on 2022-02-28 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_company_name_remove_mobile_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='name',
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default=True, max_length=120),
        ),
        migrations.AddField(
            model_name='mobile',
            name='company_name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='by', to='api.company'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='model_name',
            field=models.CharField(default=True, max_length=120, unique=True),
        ),
    ]
